from django.urls import include, path

from rest_framework.routers import DefaultRouter

from observations import views


router = DefaultRouter()
router.register("observations", views.ObservationsViewSet)  # automatically create routes based on ObservationsViewSet

app_name = "observation"

urlpatterns = [
    path("", include(router.urls))  # include routes generated by the router
]